version: '3.9'

services:
  db:
    image: "postgres:14.2-alpine"
    restart: unless-stopped
    environment:
      POSTGRES_DB: carford
      POSTGRES_USER: carford
      POSTGRES_PASSWORD: carford
    volumes:
      - db-data:/var/lib/postgresql/data

  web:
    build: .
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: password

volumes:
  db-data: